from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
import time


chrome_options = webdriver.ChromeOptions()
chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=chrome_options)

print("Started !")


driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[1])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[2])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[3])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[4])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[5])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[6])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[7])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[8])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(1)
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[9])
driver.get("https://x10cron.rock6064.repl.run")
time.sleep(50)

print("Opened all the pages !")

q = 25
w = 0
print("Started the loop")
while w < q:
  driver.switch_to.window(driver.window_handles[0])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[1])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[2])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[3])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[4])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[5])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[6])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[7])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[8])
  driver.refresh()
  time.sleep(1)
  driver.switch_to.window(driver.window_handles[9])
  driver.refresh()
  time.sleep(50)
  w = w + 1
  print(f'Loop count:{w}')

print("Completed All !")

driver.quit()
